services:
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8000"
      KEY: "${azureaikey}"
    ports:
      - "8001:8000"
      - "8003:8002"
    networks:
      - "aspire"
  chatui:
    image: "yidadaa/chatgpt-next-web:latest"
    environment:
      OPENAI_API_KEY: "demo-key"
      BASE_URL: "http://localhost:8000"
    ports:
      - "8004:3000"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
